version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyclingmetrics
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cyclingmetrics
      PORT: 4000
      UPLOAD_DIR: /data/uploads
      AUTH_ENABLED: 'false'
      NEXTAUTH_SECRET: change-me
    volumes:
      - backend-uploads:/data/uploads
    ports:
      - '4000:4000'
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
      NEXT_INTERNAL_API_URL: http://backend:4000/api
      NEXT_PUBLIC_AUTH_ENABLED: 'false'
      NEXTAUTH_SECRET: change-me
      NEXTAUTH_URL: http://localhost:3000
    ports:
      - '3000:3000'
volumes:
  postgres-data:
  backend-uploads:
